SELECT SDPID, COUNT(*) AS 'Count'
FROM MIV_CO_901
GROUP BY SDPID
HAVING (COUNT(*) > 1)
ORDER BY SDPID

SELECT M.*
FROM MIV_CO_901 M
JOIN ( SELECT SDPID, COUNT(*) AS 'Count' FROM MIV_CO_901 GROUP BY SDPID HAVING COUNT(*) > 1) B
ON M.SDPID = B.SDPID
ORDER BY M.SDPID

SELECT * FROM MIV_CO_901 WHERE SDPID = '379751300160010001'