SELECT C.CustomCIS2 AS 'WorkRequestNumber'
	, C.Customerid AS 'ProField ID'
	, C.UtilityServiceID AS 'TransactionType'
	, C.PremiseNumber AS 'SDPID'
	, C.ServiceType
	, C.CustomerNumber AS 'AccountNumber'
	, C.LegacyMeterSerial AS 'LegacyMeterNumber'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'ModuleID') AS 'LegacyModuleNumber'
	,  CASE WHEN C.UtilityServiceID = 'Meter_Set' THEN NULL
		ELSE (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'LegacyMeterManufacturer') 
		END AS 'LegacyMeterManufacturerCode'
	, CASE WHEN C.UtilityServiceID = 'Meter_Set' THEN NULL
		ELSE (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'CECONYMeterType')
		END AS 'LegacyMeterType'
	, C.LegacyMeterReading, C.LegacyMeterReading2,C.LegacyMeterReading3, C.LegacyMeterReading4, C.LegacyMeterReading5, C.LegacyMeterReading6
	, C.LegacyMeterReading7, C.LegacyMeterReading8
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'LastRead9') AS 'LegacyMeterReading9'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'LastRead10') AS 'LegacyMeterReading10'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead11')AS 'LegacyMeterReading11'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead12')AS 'LegacyMeterReading12'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead13')AS 'LegacyMeterReading13'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead14')AS 'LegacyMeterReading14'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead15')AS 'LegacyMeterReading15'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead16')AS 'LegacyMeterReading16'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead17')AS 'LegacyMeterReading17'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead18')AS 'LegacyMeterReading18'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead19')AS 'LegacyMeterReading19'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead20')AS 'LegacyMeterReading20'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead21')AS 'LegacyMeterReading21'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead22')AS 'LegacyMeterReading22'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='LastRead23')AS 'LegacyMeterReading23'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='DriveRate')AS 'AsFoundCCF'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='DriveRate')AS 'LegacyIndexDriveRate'
	, CASE WHEN C.NewMeterSerial = '' THEN (SELECT value From CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId and CI.[KEY] LIKE 'newsocketapseri%') ELSE C.NewMeterSerial END AS 'NewMeterNumber'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='NewMeterModuleNumber')AS 'NewMeterModuleNumber'  
	, NULL AS 'NewMeterManufacturerCode'
	, 6 AS 'NewMeterDialCode'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='NewMeterPrefix')AS 'NewMeterPrefix'
	, NULL AS 'NewMeterProgramID'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] ='NewMeterType')AS 'NewMeterType'
	, NULL AS 'NewMeterBillingConstant'
	, C.NewMeterRead AS 'NewMeterReading1', C.NewMeterRead2 AS 'NewMeterReading2', C.NewMeterRead3 AS 'NewMeterReading3', C.NewMeterRead4 AS 'NewMeterReading4', C.NewMeterRead5 AS 'NewMeterReading5', C.NewMeterRead6 AS 'NewMeterReading6', C.NewMeterRead7 AS 'NewMeterReading7',C.NewMeterRead8 AS 'NewMeterReading8'
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead9 ')AS 'NewMeterReading9 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead10 ')AS 'NewMeterReading10 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead11 ')AS 'NewMeterReading11 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead12 ')AS 'NewMeterReading12 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead13 ')AS 'NewMeterReading13 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead14 ')AS 'NewMeterReading14 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead15 ')AS 'NewMeterReading15 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead16 ')AS 'NewMeterReading16 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead17 ')AS 'NewMeterReading17 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead18 ')AS 'NewMeterReading18 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead19 ')AS 'NewMeterReading19 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead20 ')AS 'NewMeterReading20 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead21 ')AS 'NewMeterReading21 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead22 ')AS 'NewMeterReading22 '
	,(SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterRead23 ')AS 'NewMeterReading23 '
	, NULL AS 'AsLeftCCF'
	, NULL AS 'IndexDriveRate'
	, NULL AS 'IndexExchangeFlag'
	, CONVERT (datetime, SWITCHOFFSET(Convert(datetimeoffset, (SELECT TOP 1  JE.EventDate FROM JobEvent JE WHERE J.JobId = JE.JobId AND JE.Title LIKE 'Assigned')), DATENAME(Tzoffset,SYSDATETIMEOFFSET()))) AS 'JobCreatedDateTime'
	, CONVERT (datetime, SWITCHOFFSET(Convert(datetimeoffset, (SELECT TOP 1  JE.EventDate FROM JobEvent JE WHERE J.JobId = JE.JobId AND JE.Title LIKE 'Job Completed')), DATENAME(Tzoffset,SYSDATETIMEOFFSET()))) AS 'JobCompletionDate'
	, C.GPSLatitude AS 'Latitude'
	, C.GPSLongitude AS 'Longitude'
	, CASE WHEN C.GPSLocation = 3 THEN 'GPS Unavailable' 
			WHEN C.GPSLocation = 2 THEN 'Building Entrance'
			WHEN C.GPSLocation = 1 THEN 'Meter Pan Location'
			ELSE ''
			END AS 'GPSCollectionCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterStatus')AS 'MeterStatus'
	, CASE WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Socket Locked' THEN '1' 
			WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Bottom Locked' THEN '2' 
			WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Adapter Locked' THEN '3' 
			WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Socket Unlocked' THEN '4' 
			WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Bottom Unlocked' THEN '5' 
			WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Adapter Unlocked' THEN '6' 
			WHEN (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLockCode') = 'Electric Meter Unlockable' THEN '7' 
			ELSE ''
			END AS 'NewMeterLockCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterLocation')AS 'MeterLocation'
	, C.BillingCycle AS 'BillingCycleTrip'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MeterServiceClass')AS 'MeterServiceClass'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'DemandMeterCode')AS 'DemandMeterClassCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'TimeOfDayCode')AS 'TimeOfDayCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'TensionCode')AS 'HiLoTensionCode'
	, C.Address
	, C.PostalCode AS 'Zip'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'Municipality')AS 'Municipality'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'AccessControlCode')AS 'AccessControlCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MultiDwellingUnit')AS 'MultiDwellingAccountCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'MultiMeterCode')AS 'MultiMeterCode'
	, 'N' AS 'GasOnlyCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'NewMeterSocketVoltage')AS 'VoltageofSDP'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'InstallationCompany')AS 'CompanyCode'
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'EmployeeID')AS 'EMPId'
	, Concat(PU.FirstName, ' ', PU.LastName) AS 'Installer' 
	, (SELECT value FROM CustomCustomerInfo CI WHERE C.CustomerId = CI.CustomerId AND CI.[KEY] = 'InstallerComments')AS 'InstallerComments'
	, NULL AS 'NewMeterStatus'
	, C.District
FROM Customer C
INNER JOIN Job J 
ON J.JobTrackingGuid = C.ActiveJobGuid
INNER JOIN ProFieldCore.dbo.ProFieldUser PU
ON PU.UserId = J.TechId
WHERE J.EndTime BETWEEN '2018-09-18 00:01:46.970' AND '2018-09-18 23:51:46.970'
AND C.SiteStatus = 'Certified'
AND (C.UtilityServiceID IN ('METER_EXCHANGE', 'METER_SET', 'METER_REMOVE') OR (C.UtilityServiceID LIKE 'RIC%' AND (SELECT value FROM CustomCustomerInfo CI WHERE CI.CustomerId = C.CustomerId AND CI.[KEY] = 'IsMeterExchanged' ) = 'Y' ) ) 
--AND (SELECT value FROM CustomCustomerInfo CI WHERE CI.CustomerId = C.CustomerId AND CI.[KEY] = 'IsMeterExchanged' ) = 'N'
ORDER BY J.EndTime ASC;

